version: '3.8'
services:
  fastapi:
    image: ghcr.io/hamishgibbs/meal_prep_ai:latest
    container_name: meal_prep_ai
    ports:
      - "8022:8022"
    volumes:
      - meal_prep_ai_data:/app/data

volumes:
  meal_prep_ai_data: